=== ndtai772/INT3505-1-Service-oriented-architecture/week_03/schema.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="personalInfo">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="surname" type="xs:string" />
				<xs:element name="givenName" type="xs:string" />
				<xs:element name="dateOfBirth" type="xs:date" />
				<xs:element name="studentId">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:pattern value="[0-9]{8}"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="gender">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:pattern value="male|female|other"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="emails">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="vnuMail" type="xs:string" />
							<xs:element name="otherMail" type="xs:string" minOccurs="0"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="family">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="person" minOccurs="1" maxOccurs="2">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="fullName" type="xs:string" />
										<xs:element name="address" type="xs:string" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== ndtai772/INT3505-1-Service-oriented-architecture/week_03/example_valid.xml
<?xml version="1.0" encoding="utf-8"?>
<personalInfo xsi:noNamespaceSchemaLocation="schema.xsd"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <surname>Nguyễn Đức</surname>
    <givenName>Tài</givenName>
    <dateOfBirth>2000-07-07</dateOfBirth>
    <studentId>18021111</studentId>
    <gender>male</gender>
    <emails>
        <vnuMail>18021111@vnu.edu.vn</vnuMail>
        <otherMail>ndtai772@gmail.com</otherMail>
    </emails>
    <family>
        <person>
            <fullName>Phan Thị Thảo</fullName>
            <address>Anh Sơn, Nghệ An</address>
        </person>
        <person>
            <fullName>Phan Thị Thảo</fullName>
            <address>Anh Sơn, Nghệ An</address>
        </person>
    </family>
</personalInfo>
